In [1]:
import numpy as np 
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 

In [2]:
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [3]:
np.argmax(a)

7

In [4]:
np.argmax(a,0)

array([1, 2, 0])

In [5]:
np.argmax(a,1)

array([2, 0, 1])

In [6]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]]) 
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [7]:
np.nonzero(a)

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 1, 2, 0, 2]))

In [9]:
x,y=np.where(a==0)

In [10]:
a[x,y]

array([0, 0, 0])

In [18]:
#bool 연산은 반드시 괄호로 묶은 다음 and, or 등 처리해야 한다.
x,y=np.where((a>10) & (a<=50))

In [19]:
a[x,y]

array([30, 40, 20, 50])

In [21]:
np.extract(np.mod(a,4)==0,a)

array([40,  0,  0, 20,  0, 60])

## 코드 악보

In [ ]:
import numpy as np
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
np.argmax(a)
np.argmax(a,0)
np.argmax(a,1)
np.nonzero(a)
np.where(a==0)
np.where((a>10)&(a<=50))
np.extract(np.mid(a,4)==0,a)