In [19]:
import numpy as np
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
],dtype='int64')

In [20]:
v=np.array([1,0,1])

In [21]:
y=np.empty_like(x,dtype='int64')

In [22]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
print(y)

[[94240456369088              0              0]
 [             0              0              0]
 [             0              0              0]
 [             0              0              0]]


In [24]:
#2차원의 크기가 3인데 v의 크기도 3이다.
for i in range(4):
    y[i,:]=x[i,:]+v

In [25]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [26]:
#Broadcasting으로 표현하면 다음과 같다.
#1차원 -> 2차원(여기서) v와 합쳐진다. -> shape=(1차원,2차원,)
x[:,:]+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [27]:
y[:,:]=x[:,:]+v

In [28]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [31]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
v=np.array([1,0,1])
vv=np.tile(v,reps=(4,1)) #반복해서 쌓기
print(x)
print('-v-')
print(v)
print('-vv-')
print(vv)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-v-
[1 0 1]
-vv-
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [33]:
np.tile(v,reps=(4,2))

array([[1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1]])

In [34]:
np.tile(v,(4,1))

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [35]:
print(x+vv)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
print(x+v) #broadcasting, 차원의 크기를 자동으로 맞춘다.

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [19]:
import numpy as np
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
],dtype='int64')

v=np.array([1,0,1])
y=np.empty_like(x,dtype='int64')

#2차원의 크기가 3인데 v의 크기도 3이다.
for i in range(4):
    y[i,:]=x[i,:]+v
#Broadcasting으로 표현하면 다음과 같다.
#1차원 -> 2차원(여기서) v와 합쳐진다. -> shape=(1차원,2차원,)
x[:,:]+v

y[:,:]=x[:,:]+v

x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
v=np.array([1,0,1])
vv=np.tile(v,reps=(4,1)) #반복해서 쌓기