In [1]:
import numpy as np
x=np.array([
    [1,2],
    [3,4]
])
y=np.array([
    [5,6],
    [7,8]
])

In [2]:
v=np.array([9,10])
w=np.array([11,12])

In [3]:
print(v.dot(w)) #dot production (원소별로 곱해서 합친다)

219


In [4]:
9*11+10*12

219

In [5]:
print(np.dot(v,w))

219


In [6]:
print(x)
print("---")
print(y)
print("===")
print(x.dot(y)) #행렬곱

[[1 2]
 [3 4]]
---
[[5 6]
 [7 8]]
===
[[19 22]
 [43 50]]


In [7]:
print("M(1,1)=",1*5+2*7)
print("M(1,2)=",1*6+2*8)
print("M(2,1)=",3*5+4*7)
print("M(2,2)=",3*6+4*8)

M(1,1)= 19
M(1,2)= 22
M(2,1)= 43
M(2,2)= 50


In [8]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


# Code Score

In [1]:
import numpy as np
x=np.array([
    [1,2],
    [3,4]
])
y=np.array([
    [5,6],
    [7,8]
])

v=np.array([9,10])
w=np.array([11,12])

print(v.dot(w)) #dot production (원소별로 곱해서 합친다)

print(np.dot(v,w))

print(x.dot(y)) #행렬곱

print(np.dot(x,y))