In [1]:
import numpy as np
a=np.array([
    [30,40,70],
    [80,20,10],
    [50,90,60]
])

In [2]:
print(a)

[[30 40 70]
 [80 20 10]
 [50 90 60]]


In [3]:
np.percentile(a,50)

50.0

In [4]:
np.percentile(a,50,0)

array([50., 40., 60.])

In [5]:
np.percentile(a,50,1)

array([40., 20., 60.])

In [6]:
np.median(a)

50.0

In [7]:
np.median(a,0)

array([50., 40., 60.])

In [8]:
np.median(a,1)

array([40., 20., 60.])

In [9]:
np.mean(a)

50.0

In [10]:
np.mean(a,0)

array([53.33333333, 50.        , 46.66666667])

In [11]:
np.mean(a,1)

array([46.66666667, 36.66666667, 66.66666667])

In [16]:
np.average(a,weights=[4,3,3],axis=0)

array([51., 49., 49.])

In [19]:
a=np.random.randint(0,10,5) #low, high, size for each

In [20]:
a

array([3, 4, 9, 7, 0])

In [21]:
np.std(a) #standard deviation

3.1368774282716245

In [22]:
np.var(a) #variance

9.84

In [23]:
np.sort(a)

array([0, 3, 4, 7, 9])

In [24]:
np.sort(a,kind='mergesort') #recommend

array([0, 3, 4, 7, 9])

In [25]:
np.sort(a,kind='heapsort')

array([0, 3, 4, 7, 9])

In [26]:
np.sort(a,kind='quicksort') #default

array([0, 3, 4, 7, 9])

In [48]:
dt=np.dtype([
    ('name','S10'),
    ('age','int32')
])
a=np.array([
    ('park',31),
    ('lee',42),
    ('kim',20)
],dtype=dt)

In [49]:
a

array([(b'park', 31), (b'lee', 42), (b'kim', 20)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [50]:
np.sort(a,kind='mergesort',order='name')

array([(b'kim', 20), (b'lee', 42), (b'park', 31)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [51]:
np.sort(a,kind='mergesrt',order='age')

array([(b'kim', 20), (b'park', 31), (b'lee', 42)],
      dtype=[('name', 'S10'), ('age', '<i4')])

# Code Score

In [ ]:
import numpy as np
a=np.array([
    [30,40,70],
    [80,20,10],
    [50,90,60]
])
np.percentile(a,50)
np.percentile(a,50,0)
np.percentile(a,50,1)
np.median(a)
np.median(a,0)
np.median(a,1)
np.mean(a)
np.mean(a,0)
np.mean(a,1)
np.std(a)
np.std(a,0)
np.std(a,1)
np.var(a)