In [3]:
import numpy as np
x=np.array([
    [1,2],
    [3,4],
],dtype="float64")
y=np.array([
    [5,6],
    [7,8],
],dtype='float64')

In [4]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [5]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [6]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [7]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [9]:
print(x)
print("---")
print(y)
print("===")
print(x*y) #위치별로 곱하기

[[1. 2.]
 [3. 4.]]
---
[[5. 6.]
 [7. 8.]]
===
[[ 5. 12.]
 [21. 32.]]


In [10]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [11]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [12]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Code Score

In [3]:
import numpy as np
x=np.array([
    [1,2],
    [3,4],
],dtype="float64")
y=np.array([
    [5,6],
    [7,8],
],dtype='float64')

print(x+y)

print(np.add(x,y))

print(x-y)

print(np.subtract(x,y))

print(x*y) #위치별로 곱하기

print(np.multiply(x,y))

print(x/y)

print(np.divide(x,y))