In [1]:
import numpy as np
a=np.array([1,10,100,1000])
print(a)

[   1   10  100 1000]


In [2]:
print(np.power(a,2))

[      1     100   10000 1000000]


In [3]:
print(np.power(a,[0,1,2,3]))

[         1         10      10000 1000000000]


In [4]:
#나머지
a=np.array([10,20,30])
b=np.array([3,5,7])
print(np.mod(a,b))

[1 0 2]


In [5]:
#mod=remainder
print(np.remainder(a,b))

[1 0 2]


In [6]:
#array min, array max
a=np.array([
    [3,7,5],
    [8,4,3],
    [2,4,9]
])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [8]:
print(np.amin(a))

2


In [10]:
print(np.amin(a,0)) #compress rows

[2 4 3]


In [11]:
print(np.amin(a,1)) #compress columns

[3 3 2]


In [12]:
print(np.amax(a))

9


In [13]:
print(np.amax(a,0))

[8 7 9]


In [14]:
print(np.amax(a,1))

[7 8 9]


In [15]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [17]:
np.ptp(a) #ptp = max - min = 9 - 2 =7

7

In [18]:
np.ptp(a,0)

array([6, 3, 6])

In [19]:
np.ptp(a,1)

array([4, 5, 7])

# Code Score

In [ ]:
import numpy as np
a=np.array([1,10,100,1000])
print(np.power(a,2))
print(np.power(a,[0,1,2,3]))
a=np.array([10,20,30])
b=np.array([3,5,7])
print(np.mod(a,b))
print(np.remainder(a,b))
a=np.array([
    [3,7,5],
    [8,4,3],
    [2,4,9]
])
print(np.amin(a))
print(np.amin(a,0)) #compress rows
print(np.amax(a))
np.ptp(a) #ptp = max - min = 9 - 2 =7
np.ptp(a,0)
np.ptp(a,1)