In [1]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(np.sum(x)) #전체 원소의 합
print(x.T) #전치행렬(행과 열을 바꿈)

[[1 2]
 [3 4]]
10
[[1 3]
 [2 4]]


In [2]:
print(np.sum(x,axis=0)) #행을 축소

[4 6]


In [3]:
print(np.sum(x,axis=1)) #열을 축소

[3 7]


# Code Score

In [1]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(np.sum(x)) #전체 원소의 합
print(x.T) #전치행렬(행과 열을 바꿈)
print(np.sum(x,axis=0)) #행을 축소
print(np.sum(x,axis=1)) #열을 축소

[[1 2]
 [3 4]]
10
[[1 3]
 [2 4]]
