In [1]:
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
i1=a>2
i1

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [2]:
print(a[i1])

[3 4 5 6]


In [4]:
a[i1]=100
print(a)

[[  1   2]
 [100 100]
 [100 100]]


# Code Score

In [1]:
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
i1=a>2

print(a[i1])

a[i1]=100
print(a)

array([[False, False],
       [ True,  True],
       [ True,  True]])