In [2]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
a

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])

In [3]:
np.unique(a)

array([2, 5, 6, 7, 8, 9])

In [6]:
np.unique(a,return_index=True)

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 4, 7, 9]))

In [7]:
np.unique(a,return_inverse=True)

(array([2, 5, 6, 7, 8, 9]), array([1, 0, 2, 0, 3, 1, 2, 4, 0, 5]))

In [9]:
np.unique(a,return_counts=True)

(array([2, 5, 6, 7, 8, 9]), array([3, 2, 2, 1, 1, 1]))

# Code Score

In [2]:
import numpy as np
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
np.unique(a)
np.unique(a,return_index=True)
np.unique(a,return_inverse=True)
np.unique(a,return_counts=True)

array([5, 2, 6, 2, 7, 5, 6, 8, 2, 9])