In [1]:
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
#인덱싱(indexing)
a1=a[[0,1,2],
    [0,1,0]]
print(a1)

[1 4 5]


In [2]:
a2=a[[0,0],[1,1]]

In [3]:
print(a2)

[2 2]


In [4]:
#0부터 n-1까지 시퀀스 배열 생성
np.arange(4)

array([0, 1, 2, 3])

In [6]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
a3=a[np.arange(4),[0,2,0,1]]
print(a3)

[ 1  6  7 11]


# Code Score

In [1]:
import numpy as np
a=np.array([
    [1,2],
    [3,4],
    [5,6]
])
#인덱싱(indexing)
a1=a[[0,1,2],
    [0,1,0]]
print(a1)

a2=a[[0,0],[1,1]]

print(a2)

#0부터 n-1까지 시퀀스 배열 생성
np.arange(4)

a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
a3=a[np.arange(4),[0,2,0,1]]
print(a3)

[1 4 5]
