In [1]:
import numpy as np
#모든 원소가 0인 shape=(2,2,)
a=np.zeros((2,2))
print(a.shape)
print(a)

(2, 2)
[[0. 0.]
 [0. 0.]]


In [2]:
b=np.ones((10,))
#모든 원소가 1인 shape=(10,)
print(b.shape)
print(b)

(10,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
c=np.full((2,2,),7)
#모든 원소가 7인 shape=(2,2,)
print(c)

[[7 7]
 [7 7]]


In [4]:
d=np.eye(3)
#대각 행렬의 원소가 1이고 나머지가 0인(identity matrix) shape=(3,3,)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
e=np.random.random((2,2))
#0에서 1까지 난수, shape=(2,2,)
print(e)

[[0.00073935 0.68818248]
 [0.22425516 0.64224051]]


# Code Score

In [1]:
import numpy as np

a=np.zeros((2,2))

b=np.ones((10,))

c=np.full((2,2,),7)

d=np.eye(3)

e=np.random.random((2,2))

(2, 2)
[[0. 0.]
 [0. 0.]]
