In [7]:
import numpy as np
import numpy.matlib

In [2]:
#행렬

In [5]:
np.matlib.empty((2,2))

matrix([[4.65927083e-310, 4.65926616e-310],
        [6.94946589e-310, 6.94946589e-310]])

In [8]:
np.matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [9]:
np.matlib.ones((3,3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
np.matlib.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
np.matlib.eye(3,4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [13]:
np.matlib.rand(3,3)

matrix([[0.13345393, 0.79203546, 0.32565144],
        [0.53894733, 0.0503558 , 0.13660254],
        [0.62307591, 0.11436689, 0.25766667]])

In [15]:
np.matrix('1,2,3;4,5,6;7,8,9')

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## 코드 악보

In [ ]:
import numpy as np
import numpy.matlib
np.matlib.empty((2,2))
np.matlib.zeros((2,2))
np.matlib.ones((3,3))
np.matlib.eye(5)
np.matlib.eye((3,4))
np.matlib.rand(3,3)
np.matrix('1,2,3;4,5,6;7,8,9')