In [1]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

In [2]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.append(a,[[7,8,9]],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.append(a,[[8],[9]],axis=1)

array([[1, 2, 3, 8],
       [4, 5, 6, 9]])

In [10]:
np.insert(a,1,[1,1,1])

array([1, 1, 1, 1, 2, 3, 4, 5, 6])

In [11]:
np.insert(a,1,[[1,1,1]],axis=0)

array([[1, 2, 3],
       [1, 1, 1],
       [4, 5, 6]])

In [14]:
np.insert(a,1,[[10,10],[100,100]],axis=1)

array([[  1,  10, 100,   2,   3],
       [  4,  10, 100,   5,   6]])

In [15]:
np.delete(a,1)

array([1, 3, 4, 5, 6])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.delete(a,1,axis=1)

array([[1, 3],
       [4, 6]])

In [18]:
np.delete(a,1,axis=0)

array([[1, 2, 3]])

# Code Score

In [1]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 

np.append(a,[7,8,9])

np.append(a,[[7,8,9]],axis=0)

np.append(a,[[8],[9]],axis=1)

np.insert(a,1,[1,1,1])

np.insert(a,1,[[1,1,1]],axis=0)

np.insert(a,1,[[10,10],[100,100]],axis=1)

np.delete(a,1)

np.delete(a,1,axis=1)

np.delete(a,1,axis=0)