In [1]:
import numpy as np
v=np.array([1,2,3])
w=np.array([4,5])
np.shape(v)

(3,)

In [2]:
np.reshape(v,(3,1))

array([[1],
       [2],
       [3]])

In [3]:
v.reshape(3,1)

array([[1],
       [2],
       [3]])

In [4]:
v.reshape((3,1))

array([[1],
       [2],
       [3]])

In [5]:
print(w)

[4 5]


In [6]:
v.reshape(3,1)*w #broadcasting

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [8]:
v.reshape((3,1,))+w #broadcasting

array([[5, 6],
       [6, 7],
       [7, 8]])

In [12]:
x=np.array([
    [1,2,3],
    [4,5,6]
])
print('-x-')
print(x)
print('-w-')
print(w)
print('---')
print((x.T+w))
print('---')
print((x.T+w).T)

-x-
[[1 2 3]
 [4 5 6]]
-w-
[4 5]
---
[[ 5  9]
 [ 6 10]
 [ 7 11]]
---
[[ 5  6  7]
 [ 9 10 11]]


In [13]:
print(x+np.reshape(w,(2,1)))

[[ 5  6  7]
 [ 9 10 11]]


# Code Score

In [1]:
import numpy as np
v=np.array([1,2,3])
w=np.array([4,5])
np.shape(v)
np.reshape(v,(3,1))
v.reshape(3,1)
v.reshape((3,1))
v.reshape(3,1)*w #broadcasting
v.reshape((3,1,))+w #broadcasting

(3,)