In [2]:
import numpy as np
a=np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b=np.array([[2,1],[4,3],[6,5]])
b

array([[2, 1],
       [4, 3],
       [6, 5]])

In [7]:
b.flatten(order='F') #f-style ordering

array([2, 4, 6, 1, 3, 5])

In [8]:
b.flatten()

array([2, 1, 4, 3, 6, 5])

In [9]:
a.flat

In [10]:
a.flat[0]

0

In [11]:
a.flat[2]

2

In [12]:
b.flat[2]

4

In [16]:
b.flat[5]

5

# Code Score

In [ ]:
import numpy as np
a=np.arange(10).reshape(5,2)
a.flat[0]
b=np.array([[2,1],[4,3],[6,5]])
b.flatten(order='F') #f-style ordering
b.flatten()