In [1]:
import numpy as np
a=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [2]:
b=a[:2,1:3]
# :2 -> [[1,2,3,4],[5,6,7,8]]
# 1:3 -> [2,3], [6,7]
print(b.shape)
print(b)

(2, 2)
[[2 3]
 [6 7]]


In [3]:
#정확한 값
print(a[0,1])

2


In [4]:
#대입
b[0,0]=77
print(a[0,1])

77


In [5]:
#뒤에서 부터
a[-1,1:3]

array([10, 11])

In [8]:
#뒤에서 부터
a[-3:-1,1:3]

array([[77,  3],
       [ 6,  7]])

In [9]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
#1차원 두 번째 지정하고 2차원에서는 전부
print(a[1,:])

[5 6 7 8]


In [11]:
#2차원에서 두번째 원소 모두
print(a[:,1])

[77  6 10]


# Code Score

In [1]:
import numpy as np
a=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

b=a[:2,1:3]
# :2 -> [[1,2,3,4],[5,6,7,8]]
# 1:3 -> [2,3], [6,7]
print(b.shape)
print(b)

#정확한 값
print(a[0,1])

#대입
b[0,0]=77
print(a[0,1])

#뒤에서 부터
a[-1,1:3]

#뒤에서 부터
a[-3:-1,1:3]

print(a)

#1차원 두 번째 지정하고 2차원에서는 전부
print(a[1,:])

#2차원에서 두번째 원소 모두
print(a[:,1])