In [1]:
import numpy as np
np.inner(np.array([1,2,3]),np.array([0,1,0]))

2

In [3]:
np.inner(np.matrix('1,2;3,4'),np.matrix('11,12;13,14'))

matrix([[35, 41],
        [81, 95]])

In [4]:
np.matmul(np.matrix('1,2;3,4'),np.matrix('11,12;13,14'))

matrix([[37, 40],
        [85, 92]])

In [5]:
a=np.array([[1,2],[3,4]]) #2,2 tensor = matrix
a

array([[1, 2],
       [3, 4]])

In [7]:
#get a determinant
print(np.around(np.linalg.det(a),4)) #linear algebra (linalg)

-2.0


In [12]:
a=np.array([
    [1,2],
    [3,5]
])
b=np.array([1,2])
solution=np.linalg.solve(a,b)
x=np.around(solution.flat[0],4)
y=np.around(solution.flat[1],4)
print(x)
print(y)

-1.0
1.0


In [13]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 

In [14]:
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## 코드 악보

In [ ]:
import numpy as np
np.inner(np.array([1,2,3]),np.array([0,1,0]))
np.inner(np.matrix('1,2;3,4'),np.matrix('11,12;13,14'))
np.matmul(np.matrix('1,2;3,4'),np.matrix('11,12;13,14'))
np.around(np.linalg.det(np.array([[1,2],[3,4]])),4)
a=np.array([[1,2],[3,4]])
b=np.array([1,2])
solution=np.linalg.solve(a,b)
np.linalg.inv(a)